<?php
defined('ABSPATH') || die('Access Denied');

if ( isset($settings->gallery_id) ) {
  ob_start();
  // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Intentional output of trusted HTML and JS generated by the plugin.
  echo REACGLibrary::get_rest_routs(intval($settings->gallery_id));
  if ( class_exists('FLBuilderModel') && FLBuilderModel::is_builder_active() ) {
    ?>
    <script type="text/javascript">
      var reacgLoadApp = document.getElementById('reacg-loadApp');
      if ( reacgLoadApp ) {
        reacgLoadApp.setAttribute('data-id', 'reacg-root<?php echo esc_js(intval($settings->gallery_id)); ?>');
        reacgLoadApp.click();
      }
    </script>
    <?php
  }
  // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Intentional output of trusted HTML and JS generated by the plugin.
  echo ob_get_clean();
}
