<?php

class REACG_Elementor extends \Elementor\Widget_Base {
  /**
   * Get widget name.
   *
   * @return string
   */
  public function get_name() {
    return 'reacg-elementor';
  }

  /**
   * Get widget title.
   *
   * @return string
   */
  public function get_title() {
    return REACG_NICENAME;
  }

  /**
   * Get widget icon.
   *
   * @return string
   */
  public function get_icon() {
    return 'reacg-elementor-icon';
  }

  /**
   * Get widget category.
   *
   * @return string[]
   */
  public function get_categories() {
    return [ 'basic' ];
  }

  /**
   * Register widget controls.
   *
   * @return void
   */
  protected function register_controls() {
    $this->start_controls_section(
      'reacg_general',
      [
        'label' => __('Basic', 'regallery'),
      ]
    );

    $edit_link = add_query_arg(array( 'post_type' => REACG_CUSTOM_POST_TYPE ), admin_url('edit.php'));

    $this->add_control(
      'setup_wizard_html',
      [
        'type' => \Elementor\Controls_Manager::RAW_HTML,
        'raw' => '
<div class="reacg-spinner__wrapper reacg-hidden"><span class="spinner is-active"></span></div>
<div class="reacg-setup-wizard">
  <img width="50" height="50" src="' . esc_url(REACG_PLUGIN_URL . '/assets/images/icon.svg') . '" />
  <p>' . esc_html__("Create new gallery or select the existing one.", "regallery") . '</p>
  <div class="reacg-setup-controls">
    <button class="reacg-create-gallery">' . esc_html__("Create new gallery", "regallery") . '</button>
  </div>
</div>',
        'content_classes' => 'reacg-elementor-options',
      ]
    );
    $this->add_control(
      'post_id',
      [
        'label_block' => TRUE,
        'show_label' => FALSE,
        /* translators: 1: opening anchor tag, 2: closing anchor tag */
        'description' => sprintf(__('Add/edit galleries %1$shere%2$s.', 'regallery'), '<a target="_blank" href="' . $edit_link . '">', '</a>'),
        'type' => \Elementor\Controls_Manager::SELECT,
        'default' => 0,
        'options' => REACGLibrary::get_shortcodes(FALSE, TRUE, FALSE),
        'content_classes' => 'reacg-galleries-list',
      ]
    );
    $this->add_control(
      'gallery_images_html',
      [
        'type' => \Elementor\Controls_Manager::RAW_HTML,
        'raw' => '<div id="reacg-gallery-images"></div>',
        'content_classes' => 'reacg-elementor-options',
      ]
    );
    $this->add_control(
      'settings_html',
      [
        'type' => \Elementor\Controls_Manager::RAW_HTML,
        'raw' => '<iframe><div id="reacg_settings" class="reacg-wrapper"></div><div id="reacg-root904d749" class="reacg-wrapper reacg-gallery reacg-preview" data-options-section="1" data-plugin-version="1.17.15" data-gallery-timestamp="1748465749821" data-options-timestamp="1748789312" data-gallery-id="7" style="display: none; --reacg-thumbnails-gap: 10px;"></div></iframe>',
        'content_classes' => 'reacg-elementor-options',
      ]
    );

    $this->end_controls_section();
  }

  /**
   * Render widget output on the frontend.
   *
   * @return void
   */
  protected function render() {
    $settings = $this->get_settings_for_display();
    $post_id = intval($settings["post_id"]);

    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Intentional output of trusted HTML and JS generated by the plugin.
    echo REACGLibrary::get_rest_routs($post_id, FALSE, $this->get_id());

    $widget_id = $this->get_id();

//    if ( is_admin() ) {
//      echo '<script type="text/javascript">';
//      // Get inserted widget container by ID.
//      echo 'var widget_cont = document.querySelector(".elementor-element-' . esc_js($widget_id) . '");';
//      // Open Elementor widget settings after the gallery load.
//      echo 'if (widget_cont) { widget_cont.querySelector(".elementor-editor-widget-settings").click(); parent.reacg_reload_gallery("' . esc_js($widget_id) . '") }';
//      echo '</script>';
//    }
  }
}
