<?php

class REACG_Elementor extends \Elementor\Widget_Base {
  /**
   * Get widget name.
   *
   * @return string
   */
  public function get_name() {
    return 'reacg-elementor';
  }

  /**
   * Get widget title.
   *
   * @return string
   */
  public function get_title() {
    return REACG_NICENAME;
  }

  /**
   * Get widget icon.
   *
   * @return string
   */
  public function get_icon() {
    return 'reacg-elementor-icon';
  }

  /**
   * Get widget category.
   *
   * @return string[]
   */
  public function get_categories() {
    return [ 'basic' ];
  }

  /**
   * Register widget controls.
   *
   * @return void
   */
  protected function register_controls() {
    $this->start_controls_section(
      'reacg_general',
      [
        'label' => __('Settings', 'regallery'),
      ]
    );

    $this->add_control(
      'setup_wizard_html',
      [
        'type' => \Elementor\Controls_Manager::RAW_HTML,
        'raw' => '<div class="reacg-spinner__wrapper reacg-hidden"><span class="spinner is-active"></span></div>
<div class="reacg-setup-wizard reacg-hidden">
  <img width="50" height="50" src="' . esc_url(REACG_PLUGIN_URL . '/assets/images/icon.svg') . '" />
  <p>' . esc_html__("Create new gallery or select the existing one.", "regallery") . '</p>
  <div class="reacg-setup-controls">
    <button class="reacg-create-gallery">' . esc_html__("Create new gallery", "regallery") . '</button>
  </div>
</div>',
      ]
    );
    $galleries = REACGLibrary::get_shortcodes(FALSE, TRUE, FALSE);
    $this->add_control(
      'post_id',
      [
        'label_block' => TRUE,
        'show_label' => FALSE,
        'type' => \Elementor\Controls_Manager::SELECT,
        'default' => 0,
        'options' => $galleries,
        'content_classes' => (count($galleries) > 1 ? '' : 'reacg-hidden ') . 'reacg-elementor-options',
      ]
    );
    $this->add_control(
      'gallery_options_html',
      [
        'type' => \Elementor\Controls_Manager::RAW_HTML,
        'raw' => '<div class="reacg-spinner__wrapper reacg-hidden"><span class="spinner is-active"></span></div>
<div id="reacg-gallery-images" class="reacg-elementor-options"></div>
<div id="reacg_settings" class="reacg-elementor-options reacg-wrapper"></div>',
      ]
    );
    $this->add_control(
      'preview_html',
      [
        'type' => \Elementor\Controls_Manager::RAW_HTML,
        'raw' => '<div class="reacg-fake-container reacg-wrapper reacg-gallery reacg-preview" data-options-section="1" data-gallery-id="0" style="display: none;"></div>',
        'content_classes' => 'reacg-elementor-options',
      ]
    );

    $this->end_controls_section();
  }

  /**
   * Render widget output on the frontend.
   *
   * @return void
   */
  protected function render() {
    $settings = $this->get_settings_for_display();
    $post_id = intval($settings["post_id"]);
    $widget_id = $this->get_id();

    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Intentional output of trusted HTML and JS generated by the plugin.
    echo REACGLibrary::get_rest_routs($post_id, FALSE, $widget_id);

//    if ( is_admin() ) {
//      echo '<script type="text/javascript">';
//      echo 'parent.reacg_reload_gallery("' . esc_js($widget_id) . '", "' . esc_js($post_id) . '", false, true);';
//      echo '</script>';
//    }
  }
}
