<?php

class REACG_WPBakery {
  private $obj;
  public function __construct($obj) {
    $this->obj = $obj;
    add_shortcode( $obj->shortcode . '_wpbakery_widget', [$this, 'render_widget'] );
    $this->widget();
  }

  private function widget() {
    $options = [];
    foreach ( REACGLibrary::get_shortcodes(FALSE, TRUE, FALSE) as $id => $label ) {
      $options[ $label ] = $id;
    }
    $edit_link = add_query_arg(array( 'post_type' => REACG_CUSTOM_POST_TYPE ), admin_url('edit.php'));

    vc_map( array(
              'name' => REACG_NICENAME,
              'base' => $this->obj->shortcode . '_wpbakery_widget',
              'class' => '',
              'category' => 'Content',
              "icon" => "reacg-icon",
              'params' => array(
                array(
                  'type' => 'dropdown',
                  'heading' => __( 'Select gallery', 'regallery' ),
                  'param_name' => 'id',
                  'value' => $options,
                  /* translators: 1: opening anchor tag, 2: closing anchor tag */
                  'description' => sprintf(__('Add/edit galleries %1$shere%2$s.', 'regallery'), '<a target="_blank" href="' . $edit_link . '">', '</a>'),
                ),
              )
            ) );
  }

  public function render_widget( $atts ) {
    $atts = shortcode_atts( [ 'id' => 0 ], $atts, $this->obj->shortcode . '_wpbakery_widget' );

    $id = intval( $atts['id'] );

    ob_start();
    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Intentional output of trusted HTML and JS generated by the plugin.
    echo REACGLibrary::get_rest_routs( $id );
    // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Nonce is not required.
    if ( isset( $_GET['vc_editable'] ) && $_GET['vc_editable'] === 'true' ) {
      ?>
      <script type="text/javascript">
        var reacgLoadApp = document.getElementById('reacg-loadApp');
        if ( reacgLoadApp ) {
          reacgLoadApp.setAttribute('data-id', 'reacg-root<?php echo esc_js($id); ?>');
          reacgLoadApp.click();
        }
      </script>
      <?php
    }

    return ob_get_clean();
  }
}
